lbwebsite/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_view, name='logout'),
    re_path(r'^server/(?P<guild_id>[0-9]+)$', views.server, name='server'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/prefix$', views.server_prefix_post, name='server_prefix'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/prefix/(?P<prefix>.*)$', views.server_remove_prefix, name='server_remove_prefix'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/command/(?P<command_name>.*)$', views.server_remove_custom_command, name='server_remove_custom_command'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/guild$', views.server_add_guild_server, name='server_add_guild_server'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/guild/(?P<guild_server_id>[0-9]+)$', views.server_make_default_guild_server, name='server_default_guild_server'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/guild/(?P<guild_server_id>[0-9]+)/delete$', views.server_remove_guild_server, name='server_remove_guild_server'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/rank$', views.server_add_rank, name='server_add_rank'),
    re_path(r'^server/(?P<guild_id>[0-9]+)/rank/(?P<rank_id>.*)$', views.server_remove_rank, name='server_remove_rank'),
    path('update_realm/<str:region>', views.update_realm, name="update_realm"),
    path('myself', views.myself, name='myself'),
    path('myself/character/<int:character_id>', views.myself_update, name='update_character')
]

legendarybot/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lbwebsite.urls')),
    path('admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social'))
]

lbwebsite/models.py
from django.contrib.auth.models import User
from django.db import models, IntegrityError
from django.db.models.signals import m2m_changed
from django.dispatch import receiver


class DiscordGuild(models.Model):
    guild_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} | {self.guild_id}"


class GuildPrefix(models.Model):
    guild = models.ForeignKey(DiscordGuild, on_delete=models.CASCADE)
    prefix = models.CharField(max_length=10)
    
    class Meta:
        unique_together = (('guild', 'prefix'))


class GuildCustomCommand(models.Model):
    guild = models.ForeignKey(DiscordGuild, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    TEXT = 1

    choices = (
        (TEXT, "Text"),
    )
    type = models.IntegerField(choices=choices, default=TEXT)
    value = models.CharField(max_length=2000)

    class Meta:
        unique_together = (('guild', 'name'))


class GuildServer(models.Model):
    guild = models.ForeignKey(DiscordGuild, on_delete=models.CASCADE)

    US = 1
    EU = 2
    TW = 3
    KR = 4

    choices = (
        (US, "US"),
        (EU, "EU"),
        (TW, "TW"),
        (KR, "KR")
    )
    region = models.IntegerField(choices=choices, default=US)
    server_slug = models.CharField(max_length=50)
    guild_name = models.CharField(max_length=50, null=True)
    default = models.BooleanField(default=False)
    class Meta:
        unique_together = ("guild","region","server_slug","guild_name")

    def __str__(self):
        return f"{self.server_slug}-{self.choices[self.region - 1][1]} | {self.guild_name}"

class RealmConnected(models.Model):
    US = 1
    EU = 2
    TW = 3
    KR = 4

    choices = (
        (US, "US"),
        (EU, "EU"),
        (TW, "TW"),
        (KR, "KR")
    )
    region = models.IntegerField(choices=choices, default=US)
    server_slug = models.CharField(max_length=50)
    connected_realm = models.ManyToManyField('self')

    def __str__(self):
        return f"{self.region} - {self.server_slug}"


class Character(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    US = 1
    EU = 2
    TW = 3
    KR = 4

    choices = (
        (US, "US"),
        (EU, "EU"),
        (TW, "TW"),
        (KR, "KR"),
    )
    region = models.IntegerField(choices=choices, default=US)
    server_slug = models.CharField(max_length=50, verbose_name="Realm")
    name = models.CharField(max_length=50)
    guild_name = models.CharField(max_length=50, null=True, blank=True)
    thumbnail = models.CharField(max_length=300)
    main_for_guild = models.ManyToManyField(DiscordGuild, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.region} - {self.server_slug} - {self.name} - {self.guild_name} - {self.thumbnail}"

    def __eq__(self, other):
        if isinstance(other, Character):
            return self.region == other.region and self.server_slug == other.server_slug and self.name == other.name
        return False

    class Meta:
        unique_together = (('region', 'server_slug', 'name'))

class GuildRank(models.Model):
    guild = models.ForeignKey(DiscordGuild, on_delete=models.CASCADE)
    wow_guild = models.ForeignKey(GuildServer, on_delete=models.CASCADE)
    rank_id = models.IntegerField(verbose_name="Rank ID")
    discord_rank = models.CharField(verbose_name="Discord Rank", max_length=200)
    class Meta:
        unique_together = ("guild", "wow_guild", "rank_id")

class GuildSetting(models.Model):
    guild = models.ForeignKey(DiscordGuild, on_delete=models.CASCADE)
    setting_name = models.CharField(max_length=100)
    setting_value = models.CharField(max_length=1000)
    class Meta:
        unique_together = ("guild", "setting_name")

@receiver(m2m_changed, sender=Character.main_for_guild.through)
def verify_uniqueness_character_guild(sender, **kwargs):
    character = kwargs.get('instance', None)
    action = kwargs.get('action', None)
    guilds = kwargs.get('pk_set', None)

    if action == "pre_add":
        for guild in guilds:
            if Character.objects.filter(user=character.user).filter(main_for_guild=guild):
                raise IntegrityError('Already have a character set for this guild.')

lbwebsite/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from slugify import slugify

from lbwebsite.models import GuildServer, GuildRank
from lbwebsite.utils import execute_battlenet_request


class PrefixForm(forms.Form):
    prefix = forms.CharField(max_length=10, label='Prefix', min_length=1)


class GuildServerForm(ModelForm):
    class Meta:
        model = GuildServer
        fields = ['region', 'server_slug', 'guild_name']

    def clean(self):
        # We check if the server & guild exists.
        self.cleaned_data['server_slug'] = slugify(self.cleaned_data['server_slug'])
        r = execute_battlenet_request(f"https://{dict(GuildServer.choices)[self.cleaned_data['region']]}.api.blizzard.com/wow/guild/{self.cleaned_data['server_slug']}/{self.cleaned_data['guild_name']}")
        if not r.ok:
            raise ValidationError('Guild not found on the realm!')
        return self.cleaned_data


class GuildRankForm(ModelForm):
    class Meta:
        model = GuildRank
        fields = ['wow_guild', 'rank_id', 'discord_rank']

    def __init__(self, guild, *args, **kwargs):
        super (GuildRankForm,self ).__init__(*args,**kwargs)
        self.fields['wow_guild'].queryset = GuildServer.objects.filter(guild=guild)

lbwebsite/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from lbwebsite.decorators import is_server_admin
from lbwebsite.forms import PrefixForm, GuildServerForm, GuildRankForm
from lbwebsite.models import DiscordGuild, GuildPrefix, Character, GuildCustomCommand, GuildServer, RealmConnected, \
    GuildRank
from lbwebsite.utils import execute_battlenet_request


def index(request):
    return render(request, 'lbwebsite/index.html')


def logout_view(request):
    logout(request)
    return redirect('index')


@login_required
@is_server_admin
def server(request, guild_id):
    try:
        guild = DiscordGuild.objects.get(pk=guild_id)
    except DiscordGuild.DoesNotExist:
        guild = DiscordGuild(guild_id=guild_id)
        guild.save()
    return render(request, 'lbwebsite/server.html', {'guild': guild, 'prefix_form': PrefixForm(), 'guild_server_form': GuildServerForm(), 'guild_rank_form': GuildRankForm(guild)})


@login_required
@require_POST
@is_server_admin
def server_prefix_post(request, guild_id):
    form = PrefixForm(request.POST)
    if form.is_valid():
        guild = DiscordGuild.objects.get(pk=guild_id)
        prefix = GuildPrefix(prefix=form.cleaned_data['prefix'], guild=guild)
        prefix.save()
        messages.add_message(request, messages.SUCCESS, f'Prefix {prefix.prefix} added to the server!')
    else:
        messages.add_message(request, messages.ERROR, 'Prefix is invalid')
    return redirect('server', guild_id=guild_id)


@login_required
@is_server_admin
def server_remove_prefix(request, guild_id, prefix):
    prefix = GuildPrefix.objects.filter(prefix=prefix, guild_id=guild_id).first()
    if prefix:
        prefix.delete()
        messages.add_message(request, messages.SUCCESS, f'Prefix {prefix} removed from the server!')
    return redirect('server', guild_id=guild_id)


@login_required
@is_server_admin
def server_remove_custom_command(request, guild_id, command_name):
    custom_command = GuildCustomCommand.objects.filter(guild_id=guild_id, name=command_name).first()
    if custom_command:
        custom_command.delete()
        messages.add_message(request, messages.SUCCESS, f"Command {command_name} removed!")
    else:
        messages.add_message(request, messages.ERROR, f"Command {command_name} not found!")
    return redirect('server', guild_id=guild_id)


@login_required
@require_POST
@is_server_admin
def server_add_guild_server(request, guild_id):
    form = GuildServerForm(request.POST)
    if form.is_valid():
        guild_server = form.save(commit=False)
        try:
            GuildServer.objects.get(guild_id=guild_id, default=True)
        except GuildServer.DoesNotExist:
            guild_server.default = True
        guild_server.guild = DiscordGuild.objects.get(pk=guild_id)
        guild_server.save()
        messages.add_message(request, messages.SUCCESS, 'Server added!')
    else:
        messages.add_message(request, messages.ERROR, 'The Server is invalid!')
    return redirect('server', guild_id=guild_id)


@login_required
@is_server_admin
def server_make_default_guild_server(request, guild_id, guild_server_id):
    try:
        guild_server = GuildServer.objects.get(guild_id=guild_id, pk=guild_server_id)

        guild_server_default = GuildServer.objects.get(guild_id=guild_id, default=True)
        guild_server_default.default = False
        guild_server_default.save()
        guild_server.default = True
        guild_server.save()
        messages.add_message(request, messages.SUCCESS, 'The server has been set as the default one!')
    except GuildServer.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'The server you want to set as default does not exist!')
    return redirect('server', guild_id=guild_id)


@login_required
def myself(request):
    return render(request, 'lbwebsite/myself.html')


@login_required
def myself_update(request, character_id):
    if request.POST and request.user.is_authenticated:
        selected_servers = request.POST.getlist('servers')
        character = Character.objects.get(pk=character_id)
        if character.user == request.user:
            character.main_for_guild.clear()
            if selected_servers:
                for server in selected_servers:
                    guild = DiscordGuild.objects.get(pk=server)
                    if guild:
                        character.main_for_guild.add(guild)
                        character.save()
        messages.add_message(request, messages.SUCCESS, f'Character {character.name} modified successfully.')
    return redirect('myself')


@is_server_admin
@login_required
def server_remove_guild_server(request,guild_id, guild_server_id):
    guild_server = GuildServer.objects.get(guild_id=guild_id, pk=guild_server_id)
    guild_server.delete()
    if guild_server.default:
        guild_server_new_default = GuildServer.objects.filter(guild_id=guild_id).first()
        if guild_server_new_default:
            guild_server_new_default.default = True
            guild_server_new_default.save()
            messages.add_message(request, messages.SUCCESS, f"Guild removed. Guild {guild_server_new_default.guild_name} set as default.")
        else:
            messages.add_message(request, messages.SUCCESS, "Guild removed!")
    else:
        messages.add_message(request, messages.SUCCESS, f"Guild removed.")
    return redirect('server', guild_id=guild_id)


@login_required
@require_POST
@is_server_admin
def server_add_rank(request, guild_id):
    form = GuildRankForm(DiscordGuild.objects.get(pk=guild_id), request.POST)
    if form.is_valid():
        guild_rank = form.save(commit=False)
        if guild_rank.wow_guild.guild.guild_id == int(guild_id):
            guild_rank.guild = DiscordGuild.objects.get(pk=guild_id)
            guild_rank.save()
            messages.add_message(request, messages.SUCCESS, f"Rank added!")
        else:
            messages.add_message(request, messages.ERROR, f"This Guild doesn't exist! Please select a valid guild")
    else:
        messages.add_message(request, messages.ERROR, "Error in the rank form. Please fix the errors.")
    return redirect('server', guild_id=guild_id)


@login_required
@is_server_admin
def server_remove_rank(request, guild_id, rank_id):
    guild_rank = GuildRank.objects.get(pk=rank_id, guild_id=guild_id)
    guild_rank.delete()
    messages.add_message(request, messages.SUCCESS, f"Rank removed!")
    return redirect('server', guild_id=guild_id)

@login_required
@staff_member_required
def update_realm(request, region):
    params = {
        "locale": "en_US",
        "namespace": f"dynamic-{region}"
    }
    result = execute_battlenet_request(f"https://{region}.api.blizzard.com/data/wow/connected-realm/", params=params)
    if result.ok:
        RealmConnected.objects.filter(region=1 if region.upper() == "US" else 2).all().delete()
        connected_realms_json = result.json()
        for realm_entry in connected_realms_json['connected_realms']:
            connected_realm_entry_bnet = execute_battlenet_request(realm_entry['href'])
            realms = []
            if connected_realm_entry_bnet.ok:
                connected_realm_entry_json = connected_realm_entry_bnet.json()
                for connected_realm_entry in connected_realm_entry_json['realms']:
                    realm_database_entry = RealmConnected()
                    realm_database_entry.region = 1 if region.upper() == "US" else 2
                    realm_database_entry.server_slug = connected_realm_entry['slug']
                    realm_database_entry.save()
                    for realm in realms:
                        realm_database_entry.connected_realm.add(realm)
                        realm_database_entry.save()
                    realms.append(realm_database_entry)
    return HttpResponse("Done!")

lbwebsite/templates/lbwebsite/index.html
{% extends 'template.html' %}
{% block title %}Home{% endblock %}

lbwebsite/templates/lbwebsite/myself.html
{% extends 'template.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}My account{% endblock %}
{% block body %}
    <div class="row">
        <div class="col">
            {% bootstrap_messages %}
        </div>
    </div>

    <div class="row">
        <div class="col my-3">
            <img src="{% static 'lbwebsite/battle.net.png' %}" alt="battle.net logo" /><br />
            <div class="btn-group" role="group" aria-label="Battle.Net Login">
                <a href="{% url "social:begin" "battlenet-oauth2-us" %}" role="button" class="btn btn-primary">US</a>
                <a href="{% url "social:begin" "battlenet-oauth2-eu" %}" role="button" class="btn btn-primary">EU</a>
            </div>
        </div>
        <div class="col my-3">
            <p>Welcome to your personalised management page of the bot. Here, you can configure each discord server's main character.
                To fill the page with your characters, please click your region under the Battle.net logo</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2>Your characters</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Realm</th>
                    <th scope="col">Region</th>
                    <th scope="col">Guild</th>
                    <th scope="col">Main Character for Discord Server</th>
                </tr>
                </thead>
                <tbody>
                    {% for character in user.character_set.all %}
                        <tr>
                            <td><img src="http://render-us.worldofwarcraft.com/character/{{ character.thumbnail }}" alt="{{ character.name }}"/></td>
                            <td>{{ character.name }}</td>
                            <td>{{ character.server_slug }}</td>
                            <td>{{ character.get_region_display }}</td>
                            <td>{{ character.guild_name }}</td>
                            <td>
                                <form action="{% url 'update_character' character_id=character.pk%}" method="post">
                                    {% csrf_token %}
                                <select multiple name="servers" class="form-control form-control-sm">
                                    {% for server in servers %}
                                        <option value="{{ server.id }}" {% for guild in character.main_for_guild.all %}{% if server.id == guild.guild_id %}selected{% endif %}{% endfor %}>{{ server.name }}</option>
                                    {% endfor %}
                                </select>
                                <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

lbwebsite/templates/lbwebsite/server.html
{% extends 'template.html' %}
{% load bootstrap4 %}
{% block title %}Manage {% for server in servers %}{% if server.id == request.id %}{{ server.name }}{% endif %}{% endfor %}{% endblock %}

{% block body %}
    <div class="row">
    <div class="col">
        {% bootstrap_messages %}
    </div>
    </div>
<div class="row my-3">
    <div class="col">
        <br />
        <div class="alert alert-primary" role="alert">
            Prefixes
        </div>
        <p>Legendarybot supports multiple prefixes to trigger commands. By default, Mentioning it (<b>@LegendaryBot</b>) and the use of the <b>!</b> prefix works. Once you set a custom prefix, the <b>!</b> prefix is disabled.</p>
        {% if guild.guildprefix_set.count > 0 %}
            <table class="table">
                <tbody>
                {% for prefix in guild.guildprefix_set.all %}
                    <tr>
                        <td>{{ prefix.prefix }}</td>
                        <td><a href="{% url 'server_remove_prefix' guild_id=guild.guild_id prefix=prefix.prefix %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You currently have no prefixes</p>
        {% endif %}
        <form action="{% url 'server_prefix' guild_id=guild.guild_id %}" method="post">
            {% csrf_token %}
            {% bootstrap_form prefix_form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}


        </form>
    </div>
    <div class="col">
        <br />
        <div class="alert alert-primary" role="alert">
            Custom Commands
        </div>
        {% if guild.guildcustomcommand_set.count > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Text</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for custom_command in guild.guildcustomcommand_set.all %}
                    <tr>
                        <td>{{ custom_command.name }}</td>
                        <td>{{ custom_command.value }}</td>
                        <td><a href="{% url 'server_remove_custom_command' guild_id=guild.guild_id command_name=custom_command.name %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% endif %}
    </div>

</div>
<div class="row my-3">
    <div class="col">
        <br />
        <div class="alert alert-primary" role="alert">
            WoW Servers
        </div>
        <p>LegendaryBot supports multiple guilds to be configured under a single Discord server.</p>
        {% if guild.guildserver_set.count > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Region</th>
                        <th>Realm</th>
                        <th>Guild</th>
                        <th>Default</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for guild_server in guild.guildserver_set.all %}
                    <tr>
                        <td>{{ guild_server.get_region_display }}</td>
                        <td>{{ guild_server.server_slug }}</td>
                        <td>{{ guild_server.guild_name }}</td>
                        <td>{{ guild_server.default }}</td>
                        <td>{% if not guild_server.default %}<a href="{% url 'server_default_guild_server' guild_id=guild.guild_id guild_server_id=guild_server.pk %}"><button type="button" class="btn btn-primary">Make Default</button></a> {% endif %}<a href="{% url 'server_remove_guild_server' guild_id=guild.guild_id guild_server_id=guild_server.pk %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <h2>Add a server</h2>
        <form action="{% url 'server_add_guild_server' guild_id=guild.guild_id %}" method="post">
            {% csrf_token %}
            {% bootstrap_form guild_server_form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}


        </form>
    </div>
</div>
<div class="row my-3">
    <div class="col">
    <br />
        <div class="alert alert-primary" role="alert">
            WoW Ranks
        </div>
        <p>This section allows you to configure the bot to automaticly set the ranks of your users according to your guild's ranks.<br />
        WoW Ranks works as the following outside the game: Substract 1 to the rank number when registering a rank. For example: Ingame, the Guild Master is rank 1 but is actually rank 0</p>
        <table class="table">
            <thead>
                <tr>
                    <th>Guild</th>
                    <th>Rank ID</th>
                    <th>Discord Rank</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for guild_rank in guild.guildrank_set.all %}
                    <tr>
                        <td>{{ guild_rank.wow_guild.server_slug }}-{{ guild_rank.wow_guild.get_region_display }} {{ guild_rank.wow_guild.guild_name }}</td>
                        <td>{{ guild_rank.rank_id }}</td>
                        <td>{{ guild_rank.discord_rank }}</td>
                        <td><a href="{% url 'server_remove_rank' guild_id=guild.guild_id rank_id=guild_rank.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <form action="{% url 'server_add_rank' guild_id=guild.guild_id %}" method="post">
            {% csrf_token %}
            {% bootstrap_form guild_rank_form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock %}